### ISSUE TITLE
Ressource : Unlayer (template d'email)

### ISSUE THREAD

**Issue by LACOSTAR91** [WolfyzDev/Ressources#24]
# NOM DE LA RESSOURCE
>>> Unlayer 
# THEME DE LA RESSOURC 
(Ex. front-end, OSINT, etc ...)
>>> Template d'email
# TYPE DE LA RESSOURCE
(Entre : Site, logiciel, projet GitHub, vidéo, autres ) 
>>> Site
# DESCRIPTION DE LA RESOURCE
>>> Site internet qui permet de créer des template d'email gratuitement
# LIEN POUR ACCEDER A LA RESSOURCE (si nécessaire)
>>> https://unlayer.com/
# VOULEZ-VOUS ÊTRE NOTE CONTRIBUTEUR ? (sur Discord et sur le repo)
(oui ou non)
>>> oui pourquoi pas
# INFOS COMPLEMENTAIRES 
>>> Aucune
#  CONTACT (discord) (facultatif)
LACOSTAR91#3788

**Comment by WolfyzDev** [comment]
✅ La ressource est validé ✅ 
On commence l'ajout
