### ISSUE TITLE
Ressource : Générateur de mot de passe

### ISSUE THREAD

**Issue by Mathieu-lecool** [WolfyzDev/Ressources#39]
### Nom de la ressource

Générateur de mot de passe

### Thème de la ressource

Utilitaire

### Type de ressource

Projet Github

### Description de la ressource

Vous en avez de devoir chercher des mots de passes à chaque fois que vous créez un compte, de devoir vous rappeler quel mot de passe vous avez utiliser pour créer votre compte ? Cette application est faite pour vous ! Vous n'avez qu'à présiser combien de caractères vous souhaitez, à quel site ce mot de passe est-il associé, et hop ! Le mot de passe est enregistré !

### Lien de la ressource

https://github.com/Mathieu-lecool/Generateur-mot-de-passe

### Souhaitez-vous être noté comme contributeur ?

Oui

### Informations complémentaires

Contributeur : Mathieu-lecool

### Règles de contribution

- [X] J'accepte de suivre vos Règles de contribution

**Comment by Sn0wAlice** [comment]
XD azy fait des pull request (juste redev pas tout le code)

**Comment by Mathieu-lecool** [comment]
Je vais sur quelle brach ?

**Comment by WolfyzDev** [comment]
? Le repositories a été supprimé ?

**Comment by WolfyzDev** [comment]
> XD azy fait des pull request (juste redev pas tout le code)
Non j'ai pas touché au code. C'était juste pour faciliter l'usage du repo

**Comment by WolfyzDev** [comment]
Si quelqu'un pouvait m'expliquer svp ... @Mathieu-lecool

**Comment by ena0** [comment]
c'est probable que le repo soit privé et que donc personne ne puisse y accéder

**Comment by WolfyzDev** [comment]
> c'est probable que le repo soit privé et que donc personne ne puisse y accéder

Oui c'est possbile qu'il l'aie passé en privé. J'avais fait un fork d'ailleurs et la mention a disparu

**Comment by WolfyzDev** [comment]
Bon .. sans nouvelle prochaine, je fermerais l'issue
