### ISSUE TITLE
Setup "Retype"

### ISSUE THREAD

**Issue by WolfyzDev** [WolfyzDev/Ressources#4]
Task : Configuration Workflow "Retype" pour générer un site Web à partir des fichiers Markdown. 
[Accéder au site](https://retype.com/)

Assignees : @Sn0wAlice & @WolfyzDev 

Configuration : 
- [x]  Add a retype-action.yml file, see [step 1](https://retype.com/guides/github-actions/#step-1-add-retype-actionyml-workflow)
- [x] Configure GitHub Pages, see [step 2](https://retype.com/hosting/github-pages/#step-2-configure-github-pages)
- [x] Set the branch to retype, see [branch config](https://retype.com/hosting/github-pages/#pick-a-branch)
- [x]  Set the [url](https://retype.com/hosting/github-pages/#set-a-url)

**Comment by Sn0wAlice** [comment]
See https://github.com/WolfyzDev/Ressources/pull/6 for more step 1

For step 2: go to settings => page => select "retype" branch and click "ok"
