### ISSUE TITLE
Bug : File in VIM Cheat-Sheet

### ISSUE THREAD

**Issue by WolfyzDev** [WolfyzDev/Ressources#56]
## Screenshot

![image](https://user-images.githubusercontent.com/93478889/175109034-50ba53fb-978c-43cd-bd71-db1ea271ca29.png)

## Personne concerné 
@WolfyzDev

**Comment by ena0** [comment]
c'est pour mettre une image dans le document quand tu utilise ce format, et je suis pas sûr que ça fonctionne pour un pdf (si tu veux juste mettre le lien retiré le poi t d'interrogation)

**Comment by WolfyzDev** [comment]
> c'est pour mettre une image dans le document quand tu utilise ce format, et je suis pas sûr que ça fonctionne pour un pdf (si tu veux juste mettre le lien retire le point d'interrogation)

J'ai utilisé le même format que ce qui figurait dans la doc de Retype

**Comment by WolfyzDev** [comment]
🎉
