### ISSUE TITLE
[Ma ressource]: MobaXterm

### ISSUE THREAD

**Issue by AirbnbEcoPlus** [WolfyzDev/Ressources#66]
### Nom de la ressource

MobaXterm

### Thème de la ressource

Client SSH, Telnet, Rlogin, RDP, VNC, XDMCP, FTP, SFTP et server X11

### Type de ressource

Logiciel

### Description de la ressource

Client SSH complet avec plein d'outils comme de la Multiexecution, serveurs embarquées, plugins

### Lien de la ressource

https://mobaxterm.mobatek.net/

### Souhaitez-vous être noté comme contributeur ?

Oui

### Informations complémentaires

Pour moi le meilleur client SSH/RDP, Seul bemol pas de version sur linux 👎, Il existe aussi une version payante (50euros) mais celle gratuite et amplement suffisante

### Contact (adresse mail, discord ou autre)

AirbnbEco+#6228

### Règles de contribution

- [X] J'accepte de suivre vos Règles de contribution

**Comment by Sn0wAlice** [comment]
je valide la ressource
elle sera ajouté au plus vite

**Comment by AirbnbEcoPlus** [comment]
Cool
