### ISSUE TITLE
Ressource vidéo à venir (YaYdeYouTube)

### ISSUE THREAD

**Issue by YaYdeYouTube** [WolfyzDev/Ressources#7]
# NOM DE LA RESSOURCE
>>>
# THEME DE LA RESSOURC 
(Ex. front-end, OSINT, etc ...)
>>>
# TYPE DE LA RESSOURCE
(Entre : Site, logiciel, projet GitHub, vidéo, autres ) 
>>> 
# DESCRIPTION DE LA RESOURCE
>>>
# LIEN POUR ACCEDER A LA RESSOURCE (si nécessaire)
>>> 
# VOULEZ-VOUS ÊTRE NOTE CONTRIBUTEUR ? (sur Discord et sur le repo)
(oui ou non)
>>> 
# INFOS COMPLEMENTAIRES 
>>> 
#  CONTACT (discord) (facultatif)

**Comment by YaYdeYouTube** [comment]
Moi je vais faire la partie de vidéo youtube

**Comment by WolfyzDev** [comment]
Bonjour.  Pouvez-vous êtes plus précis ? 
Avez-vous des ressources à proposer ?

**Comment by WolfyzDev** [comment]
Bon bah je ferme l'issue ...

**Comment by WolfyzDev** [comment]
Ressource proposé

**Comment by WolfyzDev** [comment]
```cmd
npm i tuto-youtube
```
